# version format
version: 0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\lomse

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# environment variables
environment:
  FREETYPE_URL: https://github.com/ubawurinna/freetype-windows-binaries/releases/download/v2.9/freetype-2.9.zip
  UNITTESTCPP_URL: https://github.com/unittest-cpp/unittest-cpp/archive/v2.0.0.zip

# scripts that run after cloning repository
install:
  # Fetching and compiling dependencies
  - cd ..
  - mkdir ExternalLibraries
  - cd ExternalLibraries
  # Preparing FreeType
  - curl -fsSL -o freetype.zip %FREETYPE_URL%
  - 7z x -ofreetype freetype.zip
  # Preparing UnitTest++
  - curl -fsSL -o unittest-cpp.zip %UNITTESTCPP_URL%
  - 7z x unittest-cpp.zip
  - cd unittest-cpp-2.0.0
  - cmake .
  - cmake --build . --target UnitTest++
  - cd ..\.. 

# to run your custom scripts instead of automatic MSBuild
build_script:
  # Compile Lomse
  - mkdir build
  - cd build
  - cmake -DLOMSE_ENABLE_COMPRESSION=OFF -DLOMSE_ENABLE_PNG=OFF  -DFREETYPE_INCLUDE_DIRS=C:\projects\ExternalLibraries\freetype\include -DFREETYPE_LIBRARY=C:\projects\ExternalLibraries\freetype\win32\freetype.lib -DUNITTEST++_INCLUDE_DIR=C:\projects\ExternalLibraries\unittest-cpp-2.0.0\UnitTest++ -DUNITTEST++_LIBRARY=C:\projects\ExternalLibraries\unittest-cpp-2.0.0\Debug\UnitTest++.lib ../lomse
  - cmake --build .
  - copy ..\ExternalLibraries\freetype\win32\freetype.dll .\bin\Debug

# to run your custom scripts instead of automatic tests
test_script:
  # Run Lomse Tests. If failed re-run in verbose mode
  - ps: |
      .\testlib
      if (-not $?) { .\testlib -v; $host.SetShouldExit(1) }
